require "rubygems"
require "bundler/setup"
require "stringex"
require "cloudfiles"
require "mime/types"
require "find"
require "colored"
require "uri-handler"
require "digest/md5"

desc "Empty a cloudfiles container so it may be removed"
task :cloudfilesempty do
    region = get_stdin("Which region are your cloudfiles located? (uk/us): ")
    abort ("Invalid selection made") unless ["uk", "us"].include?(region)
    container = get_stdin("What is the container name? (WARNING: all contents of this container will be irrecoverably deleted): ")
    if region == "uk"
      cloudfiles_auth = CloudFiles::AUTH_UK
    elsif region == "us"
      cloudfiles_auth = CloudFiles::AUTH_US
    end

    cf = CloudFiles::Connection.new(
        :username => get_stdin("What is your cloudfiles username?: "),
        :api_key => get_stdin("What is your api key?: "),
        :auth_url => "#{cloudfiles_auth}"
    )
    container = cf.container(container)
    cdn_files = container.objects
    cdn_count = cdn_files.count
    i = 0
    cdn_files.each do |f|
        container.delete_object(f)
        print "\r Removed #{i}/#{cdn_count}"
        i+=1
    end
end

def ok_failed(condition)
    if (condition)
          puts "OK"
    else
          puts "FAILED"
    end
end

def get_stdin(message)
    print message
      STDIN.gets.chomp
end

def ask(message, valid_options)
    if valid_options
          answer = get_stdin("#{message} #{valid_options.to_s.gsub(/"/, '').gsub(/, /,'/')} ") while !valid_options.include?(answer)
    else
          answer = get_stdin(message)
   end
   answer
end

desc "list tasks"
task :list do
  puts "Tasks: #{(Rake::Task.tasks - [Rake::Task[:list]]).join(', ')}"
  puts "(type rake -T for more detail)\n\n"
end
